apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yo3fpv8by-python
  janus-idp.io/tekton: yo3fpv8by-python
  backstage.io/kubernetes-id: yo3fpv8by-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yo3fpv8by-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
