apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yo3fpv8by-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yo3fpv8by-python 
  name: yo3fpv8by-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yo3fpv8by-python 
